---
# Sysctl kernel tuning tasks

- name: Apply sysctl settings
  ansible.posix.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    sysctl_file: /etc/sysctl.d/90-ansible.conf
    reload: true
    state: present
  loop: "{{ common_sysctl_settings | dict2items }}"
  loop_control:
    label: "{{ item.key }}={{ item.value }}"
  become: true
